// e-CF Certification Wizard — 15-step configuration
// Each step defines fields, validation, instructions, and optional custom component keys.

export const STEP_CONFIG = [
  {
    step: 1,
    title: 'Solicitud',
    titleEn: 'Application',
    description: 'Registro inicial del contribuyente ante DGII',
    descriptionEn: 'Initial taxpayer registration with DGII',
    instructions: 'Recopilar los datos del contribuyente: razon social, RNC, representante legal, cedula y correo corporativo. Completar el formulario de solicitud en la DGII OFV y enviarlo.',
    clientInstructions: 'Necesitamos los siguientes documentos: RNC, cedula del representante legal y un correo corporativo activo para la comunicacion con DGII.',
    fields: [
      { key: 'razon_social', label: 'Razon Social', type: 'text', required: true },
      { key: 'representante_legal', label: 'Representante Legal', type: 'text', required: true },
      { key: 'cedula', label: 'Cedula', type: 'text', placeholder: '001-1234567-8' },
      { key: 'correo', label: 'Correo Corporativo', type: 'text', required: true },
      { key: 'submission_status', label: 'Estado', type: 'select', options: [
        { value: 'pending', label: 'Pendiente' },
        { value: 'submitted', label: 'Enviado' },
        { value: 'approved', label: 'Aprobado' },
      ]},
      { key: 'submitted_date', label: 'Fecha de Envio', type: 'date' },
    ],
    validate: (data) => !!(data?.razon_social && data?.correo),
  },
  {
    step: 2,
    title: 'Autorizacion',
    titleEn: 'Authorization',
    description: 'Autorizacion de DGII para emitir e-CF',
    descriptionEn: 'DGII authorization to issue e-CF',
    instructions: 'Verificar que la autorizacion fue recibida de la DGII. Subir el documento de autorizacion y registrar la fecha.',
    clientInstructions: 'Una vez aprobada la solicitud, la DGII enviara un documento de autorizacion a su correo corporativo. Favor reenviarlo.',
    fields: [
      { key: 'authorization_received', label: 'Autorizacion Recibida', type: 'boolean' },
      { key: 'authorization_date', label: 'Fecha de Autorizacion', type: 'date' },
      { key: 'authorization_doc', label: 'Documento de Autorizacion', type: 'file' },
      { key: 'notes', label: 'Notas', type: 'textarea' },
    ],
    validate: (data) => !!data?.authorization_received,
  },
  {
    step: 3,
    title: 'Configuracion',
    titleEn: 'Configuration',
    description: 'Instalacion de certificado digital y URLs de recepcion',
    descriptionEn: 'Digital certificate installation and receiver URLs',
    instructions: 'Instalar el certificado P12 de Viafirma en Terminal X. Configurar las URLs de recepcion y aprobacion del receptor. Verificar que el passphrase esta correcto.',
    clientInstructions: 'Necesitamos instalar el certificado digital (.p12) en su sistema. Si aun no lo tiene, coordinamos la compra con Viafirma.',
    fields: [
      { key: 'cert_uploaded', label: 'Certificado Subido', type: 'boolean' },
      { key: 'cert_filename', label: 'Nombre del Certificado', type: 'text', placeholder: 'empresa.p12' },
      { key: 'passphrase_set', label: 'Passphrase Configurado', type: 'boolean' },
      { key: 'receiver_url_recepcion', label: 'URL Recepcion', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/recepcion' },
      { key: 'receiver_url_aprobacion', label: 'URL Aprobacion', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/aprobacion' },
    ],
    validate: (data) => !!(data?.cert_uploaded && data?.passphrase_set),
  },
  {
    step: 4,
    title: 'Pruebas Simulacion',
    titleEn: 'Simulation Tests',
    description: 'Ejecucion de pruebas de simulacion ante DGII',
    descriptionEn: 'Running simulation tests with DGII',
    instructions: 'Ejecutar las pruebas de simulacion desde Terminal X. Cada tipo de e-CF debe ser enviado y aceptado por DGII. Verificar los TrackIds en la respuesta.',
    clientInstructions: 'En este paso ejecutamos pruebas automaticas con la DGII para validar que su sistema puede emitir e-CF correctamente.',
    customComponent: 'StepSimulationTests',
    fields: [],
    validate: () => false, // validated by test results
  },
  {
    step: 5,
    title: 'Representacion Impresa',
    titleEn: 'Printed Representation',
    description: 'Muestra de factura impresa con QR y datos fiscales',
    descriptionEn: 'Sample printed invoice with QR and fiscal data',
    instructions: 'Imprimir una factura de ejemplo con todos los campos fiscales requeridos: QR code, e-NCF, fecha firma, codigo seguridad. Subir foto/PDF de la muestra y enviar a DGII para revision.',
    clientInstructions: 'Necesitamos imprimir una factura de ejemplo desde su Terminal X para enviarla a la DGII para aprobacion del formato.',
    fields: [
      { key: 'sample_receipt_uploaded', label: 'Muestra Subida', type: 'boolean' },
      { key: 'sample_receipt_doc', label: 'Documento Muestra', type: 'file' },
      { key: 'dgii_feedback', label: 'Observaciones DGII', type: 'textarea' },
    ],
    validate: (data) => !!data?.sample_receipt_uploaded,
  },
  {
    step: 6,
    title: 'Revision DGII',
    titleEn: 'DGII Review',
    description: 'Revision y aprobacion de la DGII',
    descriptionEn: 'DGII review and approval',
    instructions: 'Esperar la respuesta de DGII sobre la revision de la representacion impresa y las pruebas de simulacion. Registrar el nombre del revisor y cualquier retroalimentacion.',
    clientInstructions: 'La DGII esta revisando su solicitud. Le notificaremos cuando haya respuesta.',
    fields: [
      { key: 'review_status', label: 'Estado de Revision', type: 'select', options: [
        { value: 'pending', label: 'Pendiente' },
        { value: 'in_review', label: 'En Revision' },
        { value: 'approved', label: 'Aprobado' },
        { value: 'rejected', label: 'Rechazado' },
      ]},
      { key: 'reviewer_name', label: 'Nombre del Revisor', type: 'text' },
      { key: 'feedback_notes', label: 'Notas de Retroalimentacion', type: 'textarea' },
    ],
    validate: (data) => data?.review_status === 'approved',
  },
  {
    step: 7,
    title: 'URL Servicios Prueba',
    titleEn: 'Test Service URLs',
    description: 'Configuracion de URLs de servicios en ambiente de prueba',
    descriptionEn: 'Test environment service URL configuration',
    instructions: 'Configurar y verificar las URLs de recepcion y aprobacion en el ambiente de prueba (certecf). Hacer ping a cada URL para confirmar conectividad.',
    clientInstructions: 'Estamos configurando los servicios de comunicacion con la DGII en ambiente de prueba.',
    fields: [
      { key: 'test_url_recepcion', label: 'URL Recepcion (Prueba)', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/recepcion' },
      { key: 'test_url_aprobacion', label: 'URL Aprobacion (Prueba)', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/aprobacion' },
      { key: 'connectivity_verified', label: 'Conectividad Verificada', type: 'boolean' },
    ],
    validate: (data) => !!(data?.test_url_recepcion && data?.test_url_aprobacion && data?.connectivity_verified),
  },
  {
    step: 8,
    title: 'Inicio Prueba Recepcion',
    titleEn: 'Reception Test Start',
    description: 'Inicio de pruebas de recepcion con DGII',
    descriptionEn: 'Starting reception tests with DGII',
    instructions: 'Notificar a DGII que se inician las pruebas de recepcion. Registrar la fecha de inicio y la referencia de confirmacion de DGII.',
    clientInstructions: 'Iniciamos las pruebas formales de recepcion con la DGII. Este proceso toma entre 1-3 dias.',
    fields: [
      { key: 'reception_start_date', label: 'Fecha de Inicio', type: 'date' },
      { key: 'dgii_confirmation_ref', label: 'Referencia DGII', type: 'text', placeholder: 'REF-2026-XXXXX' },
    ],
    validate: (data) => !!(data?.reception_start_date && data?.dgii_confirmation_ref),
  },
  {
    step: 9,
    title: 'Recepcion e-CF',
    titleEn: 'e-CF Reception',
    description: 'Pruebas de recepcion de e-CF completadas',
    descriptionEn: 'e-CF reception tests completed',
    instructions: 'Verificar que todas las pruebas de recepcion pasaron exitosamente. Revisar los resultados en la tabla de pruebas. Marcar como completado cuando todos los e-CF fueron recibidos correctamente.',
    clientInstructions: 'Estamos ejecutando las pruebas de recepcion de comprobantes electronicos. Le notificaremos el resultado.',
    customComponent: 'StepSimulationTests',
    fields: [
      { key: 'reception_completed', label: 'Recepcion Completada', type: 'boolean' },
    ],
    validate: (data) => !!data?.reception_completed,
  },
  {
    step: 10,
    title: 'Inicio Prueba Aprobacion',
    titleEn: 'Approval Test Start',
    description: 'Inicio de pruebas de aprobacion comercial',
    descriptionEn: 'Starting commercial approval tests',
    instructions: 'Notificar a DGII que se inician las pruebas de aprobacion comercial. Registrar la fecha y referencia.',
    clientInstructions: 'Iniciamos las pruebas de aprobacion comercial con la DGII.',
    fields: [
      { key: 'approval_start_date', label: 'Fecha de Inicio', type: 'date' },
      { key: 'dgii_confirmation_ref', label: 'Referencia DGII', type: 'text', placeholder: 'REF-2026-XXXXX' },
    ],
    validate: (data) => !!(data?.approval_start_date && data?.dgii_confirmation_ref),
  },
  {
    step: 11,
    title: 'Aprobacion Comercial',
    titleEn: 'Commercial Approval',
    description: 'Aprobacion comercial de DGII recibida',
    descriptionEn: 'DGII commercial approval received',
    instructions: 'Verificar que se recibio la aprobacion comercial de DGII. Subir el documento de aprobacion y registrar el numero de referencia y la fecha.',
    clientInstructions: 'La DGII ha emitido la aprobacion comercial. Necesitamos el documento firmado.',
    fields: [
      { key: 'approval_doc', label: 'Documento de Aprobacion', type: 'file' },
      { key: 'dgii_reference_number', label: 'Numero de Referencia DGII', type: 'text' },
      { key: 'approval_date', label: 'Fecha de Aprobacion', type: 'date' },
    ],
    validate: (data) => !!(data?.dgii_reference_number && data?.approval_date),
  },
  {
    step: 12,
    title: 'URL Servicios Produccion',
    titleEn: 'Production Service URLs',
    description: 'Configuracion de URLs de servicios en produccion',
    descriptionEn: 'Production environment service URL configuration',
    instructions: 'Configurar y verificar las URLs de recepcion y aprobacion en el ambiente de produccion (ecf). Estas son las URLs finales que usara el contribuyente.',
    clientInstructions: 'Estamos configurando los servicios finales de produccion para su facturacion electronica.',
    fields: [
      { key: 'prod_url_recepcion', label: 'URL Recepcion (Produccion)', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/recepcion' },
      { key: 'prod_url_aprobacion', label: 'URL Aprobacion (Produccion)', type: 'url', placeholder: 'https://fe.terminalxpos.com/fe/aprobacion' },
      { key: 'connectivity_verified', label: 'Conectividad Verificada', type: 'boolean' },
    ],
    validate: (data) => !!(data?.prod_url_recepcion && data?.prod_url_aprobacion && data?.connectivity_verified),
  },
  {
    step: 13,
    title: 'Declaracion Jurada',
    titleEn: 'Sworn Statement',
    description: 'Declaracion jurada notarizada del contribuyente',
    descriptionEn: 'Notarized sworn statement from taxpayer',
    instructions: 'El contribuyente debe firmar una declaracion jurada ante notario comprometiendose a cumplir con las normas de facturacion electronica. Subir el documento y registrar los datos del notario.',
    clientInstructions: 'Necesitamos que firme una declaracion jurada ante notario. Le enviaremos el modelo del documento.',
    fields: [
      { key: 'sworn_statement_doc', label: 'Declaracion Jurada', type: 'file' },
      { key: 'signed_date', label: 'Fecha de Firma', type: 'date' },
      { key: 'notary_name', label: 'Nombre del Notario', type: 'text' },
      { key: 'notary_number', label: 'Numero de Notario', type: 'text' },
    ],
    validate: (data) => !!(data?.sworn_statement_doc && data?.signed_date),
  },
  {
    step: 14,
    title: 'Verificacion Estatus',
    titleEn: 'Status Verification',
    description: 'Verificacion del estatus de certificacion en DGII',
    descriptionEn: 'Certification status verification with DGII',
    instructions: 'Verificar en el portal de DGII que el contribuyente aparece como Emisor Electronico certificado. Registrar el numero de certificacion, fecha efectiva y resolucion.',
    clientInstructions: 'Estamos verificando su estatus como Emisor Electronico certificado ante la DGII.',
    fields: [
      { key: 'certification_number', label: 'Numero de Certificacion', type: 'text' },
      { key: 'effective_date', label: 'Fecha Efectiva', type: 'date' },
      { key: 'dgii_resolution', label: 'Resolucion DGII', type: 'text' },
    ],
    validate: (data) => !!(data?.certification_number && data?.effective_date),
  },
  {
    step: 15,
    title: 'Finalizado',
    titleEn: 'Completed',
    description: 'Certificacion completada — cambiar ambiente a produccion',
    descriptionEn: 'Certification completed — switch environment to production',
    instructions: 'Verificar que todos los pasos estan completos. Cambiar el ambiente de certecf a ecf en la configuracion del cliente. Confirmar que el sistema esta emitiendo e-CF en produccion.',
    clientInstructions: 'Su certificacion esta completa. Su sistema ya puede emitir comprobantes fiscales electronicos (e-CF) en produccion.',
    customComponent: 'StepFinalized',
    fields: [],
    validate: () => false, // validated by allStepsComplete
  },
]
